apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pipeline
  name: other-something
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
