apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pipeline-operator.fullname" . }}-manager-role
  labels:
  {{- include "pipeline-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - jobs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.1eedaegon.github.io
  resources:
  - pipelines
  - pipelines/status
  - tasks
  - runs
  - runs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.1eedaegon.github.io
  resources:
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - pipeline.1eedaegon.github.io
  resources:
  - tasks/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pipeline-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pipeline-operator
    app.kubernetes.io/part-of: pipeline-operator
  {{- include "pipeline-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "pipeline-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "pipeline-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'