apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pipeline-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pipeline-operator
    app.kubernetes.io/part-of: pipeline-operator
  {{- include "pipeline-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}