# permissions for end users to view pipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pipeline-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pipeline-operator
    app.kubernetes.io/part-of: pipeline-operator
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-viewer-role
rules:
- apiGroups:
  - pipeline.1eedaegon.github.io
  resources:
  - pipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipeline.1eedaegon.github.io
  resources:
  - pipelines/status
  verbs:
  - get
