apiVersion: pipeline.1eedaegon.github.io/v1
kind: Pipeline
metadata:
  name: pipeline-chain-test-2
spec:
  volumes:
  - name: yennefer-something # 이미 있으면 생성하지 않고 사용
    capacity: 2G # 최대값  # Requests: 2Gi 최소값, csi드라이버 마다 구현이 달라서 통제가 어려움
    # storage 미정의 혹은 empty string으로 정의시 Default StorageClass 사용
    # storage: standard
    # lifecycle 미정의시 pipeline scope로 동작
    # persistent / run / pipeline (crd 정의 참고)
    # lifecycle: persistent
  resource:
    cpu: 200m
    memory: 100Mi
  tasks:
  - name: pipeline-2-1 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    - name: yennefer-something/input # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something/init-output # RWX
      useIntermediateDirectory: true
    runBefore: []
    additionalContainerSpecs: null
    additionalPodSpecs: null
  - name: pipeline-2-2 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    - name: yennefer-something/input # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something/init-output # RWX
      useIntermediateDirectory: true
    runBefore:
    - pipeline-2-1
    additionalContainerSpecs: null
    additionalPodSpecs: null
  - name: pipeline-2-3 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    - name: yennefer-something/input # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something/init-output # RWX
      useIntermediateDirectory: true
    runBefore:
    - pipeline-2-2
  additionalContainerSpecs: null
  additionalPodSpecs: null
