
apiVersion: pipeline.1eedaegon.github.io/v1
kind: Pipeline
metadata:
  name: pipeline-chain-test
spec:
  volumes:
  - name: yennefer-something # 이미 있으면 생성하지 않고 사용
    capacity: 2G # 최대값  # Requests: 2Gi 최소값, csi드라이버 마다 구현이 달라서 통제가 어려움
    storage: standard
  resource:
    cpu: 200m
    memory: 100Mi
  tasks:
  - name: pipeline-1 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs: 
    - yennefer-something/input # RO
    outputs:
    - yennefer-something/init-output # RWX
    runBefore: []
  - name: pipeline-2 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs: 
    - yennefer-something/input # RO
    outputs:
    - yennefer-something/init-output # RWX
    runBefore:
    - pipeline-1
  - name: pipeline-3 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs: 
    - yennefer-something/input # RO
    outputs:
    - yennefer-something/init-output # RWX
    runBefore:
    - pipeline-2    
