# Yennefer pipeline yaml

apiVersion: pipeline.1eedaegon.github.io/v1
kind: Pipeline
metadata:
  name: pipeline-chain-test
spec:
  schedule: # Schedule의 cron과 runAfter/runBefore가 동시에 걸리면 경고를 띄운다. 
  volumes:
  - name: yennefer-something # 이미 있으면 생성하지 않고 사용
    capacity: 2G # 최대값  # Requests: 2Gi 최소값, csi드라이버 마다 구현이 달라서 통제가 어려움
    storage: standard
  resource:
    cpu: 200m
    memory: 100Mi
  tasks:
  - name: pipeline-1 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    # runBefore와 inputs가 동시에 걸리고 runBefore의 task에 output이 없으면 경고를 띄운다.
    - name: yennefer-something/input # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something/output # RWX
      useIntermediateDirectory: true
    runBefore: []
  - name: pipeline-2-1 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    - name: yennefer-something/input # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something/pipeline-2-1-output # RWX
      useIntermediateDirectory: true
    runBefore:
    - pipeline-1
  - name: pipeline-2-2 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    - name: yennefer-something/output # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something/pipeline-2-2-output # RWX
      useIntermediateDirectory: true
    runBefore:
    - pipeline-1
  - name: pipeline-2-1-1 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    - name: yennefer-something/pipeline-2-2-output # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something/pipeline-2-1-1-output # RWX
      useIntermediateDirectory: true
    runBefore:
    - pipeline-2-1
  - name: pipeline-3 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    - name: yennefer-something/pipeline-2-1-1-output # RO
      useIntermediateDirectory: true
    - name: yennefer-something/pipeline-2-2-output # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something/pipeline-3-out # RWX
      useIntermediateDirectory: true
    runBefore:
    - pipeline-2-2
    - pipeline-2-1-1
