# Yennefer pipeline yaml

apiVersion: pipeline.1eedaegon.github.io/v1
kind: Pipeline
metadata:
  name: pipeline-chain-test-3
spec:
  schedule: # Schedule의 cron과 runAfter/runBefore가 동시에 걸리면 경고를 띄운다. 
  volumes:
  - name: yennefer-something-3 # 이미 있으면 생성하지 않고 사용
    capacity: 2G # 최대값  # Requests: 2Gi 최소값, csi드라이버 마다 구현이 달라서 통제가 어려움
    # storage 미정의 혹은 empty string으로 정의시 Default StorageClass 사용
    # storage: standard
    # lifecycle 미정의시 pipeline scope로 동작
    # persistent / run / pipeline (crd 정의 참고)
    # lifecycle: persistent
  resource:
    cpu: 200m
    memory: 100Mi
  tasks:
  - name: pipeline-3-1 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    # runBefore와 inputs가 동시에 걸리고 runBefore의 task에 output이 없으면 경고를 띄운다.
    - name: yennefer-something-3/input # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something-3/output # RWX
      useIntermediateDirectory: true
    runBefore: []
  - name: pipeline-3-2-1 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    - name: yennefer-something-3/input # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something-3/pipeline-2-1-output # RWX
      useIntermediateDirectory: true
    runBefore:
    - pipeline-3-1
  - name: pipeline-3-2-2 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    - name: yennefer-something-3/output # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something-3/pipeline-2-2-output # RWX
      useIntermediateDirectory: true
    runBefore:
    - pipeline-3-1
  - name: pipeline-3-2-2-1 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    - name: yennefer-something-3/pipeline-2-2-output # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something-3/pipeline-2-1-1-output # RWX
      useIntermediateDirectory: true
    runBefore:
    - pipeline-3-2-1
  - name: pipeline-3-3 # import task type without image version
    image: amazon/aws-cli
    trigger: false
    args:
    - --version
    - if [ -z "$SAMPLE" ]; then echo "no" else echo $SAMPLE fi
    inputs:
    - name: yennefer-something-3/pipeline-2-1-1-output # RO
      useIntermediateDirectory: true
    - name: yennefer-something-3/pipeline-2-2-output # RO
      useIntermediateDirectory: true
    outputs:
    - name: yennefer-something-3/pipeline-3-out # RWX
      useIntermediateDirectory: true
    runBefore:
    - pipeline-3-2-2
    - pipeline-3-2-1-1
  # Below are optional fields, So You could safely omit without specifying null.
  additionalContainerSpecs: null
  additionalPodSpecs: null
