apiVersion: pipeline.1eedaegon.github.io/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: task
    app.kubernetes.io/instance: task-sample
    app.kubernetes.io/part-of: pipeline-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pipeline-operator
  name: task-sample
spec:
  # TODO(user): Add fields here
