apiVersion: pipeline.1eedaegon.github.io/v1
kind: Run
metadata:
  labels:
    app.kubernetes.io/name: run
    app.kubernetes.io/instance: run-sample
    app.kubernetes.io/part-of: pipeline-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pipeline-operator
  name: run-sample
spec:
  # TODO(user): Add fields here
