apiVersion: pipeline.1eedaegon.github.io/v1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline-sample
    app.kubernetes.io/part-of: pipeline-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pipeline-operator
  name: pipeline-sample
spec:
  # TODO(user): Add fields here
