name: Generate and publish sdks to npm
description: Generate sdks from openapi.yaml and commit to git & publish sdks to npm
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        registry-url: 'https://registry.npmjs.org'
    - name: Generate typescript-axios sdk using openapi.yaml
      shell: bash
      run: >
        npx @openapitools/openapi-generator-cli generate
        -i ./generated/openapi.yaml
        -o ./generated/sdk/${{ matrix.sdk.type-shorthand }}-out
        -g ${{ matrix.sdk.type }}
    - name: Move sdk definitions into npm package using template
      shell: bash
      run: |
        mkdir -p ./generated/sdk
        rm -rf ./generated/sdk/${{ matrix.sdk.type-shorthand }}
        cp -r ./template/sdk/${{ matrix.sdk.type-shorthand }} ./generated/sdk/${{ matrix.sdk.type-shorthand }}
        mv ./generated/sdk/${{ matrix.sdk.type-shorthand }}-out/* ./generated/sdk/${{ matrix.sdk.type-shorthand }}-out/.* ./generated/sdk/${{ matrix.sdk.type-shorthand }}
        rmdir ./generated/sdk/${{ matrix.sdk.type-shorthand }}-out
    - name: Pull from remote repo
      shell: bash
      run: |
        set +e

        git add .
        git commit -m "[skip ci] Commit sdk definitions"
        git push -f origin tags/$BRANCH_NAME
        git stash apply

        set -e
        exit 0
      env:
       BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    - name: Publish ${{ matrix.sdk.type-shorthand }} sdk into npm
      shell: bash
      run: |
        cd ./generated/sdk/${{ matrix.sdk.type-shorthand }}
        npm publish --provenance --access public --tag ${{ github.sha }}
      continue-on-error: true
