name: Save openapi.yaml as artifact
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write
  pages: write

jobs:
  save-and-upload-openapi-yaml:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/build-and-push-container-image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/save-and-upload-openapi-yaml
